" Vim configuration file
"
" adding pathogen support per instructions on
"  https://github.com/tpope/vim-pathogen
execute pathogen#infect()
syntax on
filetype plugin indent on

autocmd! BufNewFile,BufRead *.pde setlocal ft=arduino
autocmd! BufNewFile,BufRead *.ino setlocal ft=arduino

set modelines=5
set nocompatible
set background=dark
" set columns=80
set ruler
set mouse=a
set number

" statusline
set laststatus=2

" searching
set incsearch
set ignorecase
set hlsearch

" set smartindent
" set tabstop=4
" Tabbing
set smarttab
set softtabstop=2
set shiftwidth=2
set expandtab

let g:solarized_termcolors=256
let g:solarized_termtrans=1

colorscheme molokai

let s:uname = system("uname -s")
if s:uname == "Linux\n"
  python3 from powerline.vim import setup as powerline_setup
  python3 powerline_setup()
  python3 del powerline_setup
endif

